# Generated by Django 5.0 on 2023-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_housing',
            field=models.CharField(choices=[('HS', 'Дом'), ('FL', 'Квартира'), ('RM', 'Комната')], default='FL', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('RT', 'Аренда'), ('SL', 'Продажа')], default='SL', max_length=2),
        ),
    ]
